In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score , confusion_matrix, classification_report

## Loading Dataset

In [9]:
data=pd.read_csv("D:/ML_datasets/PlayTennis.csv")
data

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Outlook      14 non-null     object
 1   Temperature  14 non-null     object
 2   Humidity     14 non-null     object
 3   Wind         14 non-null     object
 4   Play Tennis  14 non-null     object
dtypes: object(5)
memory usage: 692.0+ bytes

In [13]:
data.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [15]:
data.describe()

       Outlook Temperature Humidity  Wind Play Tennis
count       14          14       14    14          14
unique       3           3        2     2           2
top      Sunny        Mild     High  Weak         Yes
freq         5           6        7     8           9

In [17]:
outlook=data['Outlook'].str.get_dummies(" ")
outlook

    Overcast  Rain  Sunny
0          0     0      1
1          0     0      1
2          1     0      0
3          0     1      0
4          0     1      0
5          0     1      0
6          1     0      0
7          0     0      1
8          0     0      1
9          0     1      0
10         0     0      1
11         1     0      0
12         1     0      0
13         0     1      0

In [19]:
temp=data['Temperature'].str.get_dummies(" ")
temp

    Cool  Hot  Mild
0      0    1     0
1      0    1     0
2      0    1     0
3      0    0     1
4      1    0     0
5      1    0     0
6      1    0     0
7      0    0     1
8      1    0     0
9      0    0     1
10     0    0     1
11     0    0     1
12     0    1     0
13     0    0     1

In [21]:
humid=data['Humidity'].str.get_dummies(" ")
humid

    High  Normal
0      1       0
1      1       0
2      1       0
3      1       0
4      0       1
5      0       1
6      0       1
7      1       0
8      0       1
9      0       1
10     0       1
11     1       0
12     0       1
13     1       0

In [23]:
wind=data['Wind'].str.get_dummies(" " )
wind

    Strong  Weak
0        0     1
1        1     0
2        0     1
3        0     1
4        0     1
5        1     0
6        1     0
7        0     1
8        0     1
9        0     1
10       1     0
11       1     0
12       0     1
13       1     0

In [25]:
play=data['Play Tennis'].str.get_dummies(" ")
play

    No  Yes
0    1    0
1    1    0
2    0    1
3    0    1
4    0    1
5    1    0
6    0    1
7    1    0
8    0    1
9    0    1
10   0    1
11   0    1
12   0    1
13   1    0

## Prepare X and Y

In [28]:
data=pd.concat([outlook,temp,humid,wind,play], axis=1)
data

,Overcast,Rain,Sunny,Cool,Hot,Mild,High,Normal,Strong,Weak,No,Yes
0,0,0,1,0,1,0,1,0,0,1,1,0
1,0,0,1,0,1,0,1,0,1,0,1,0
2,1,0,0,0,1,0,1,0,0,1,0,1
3,0,1,0,0,0,1,1,0,0,1,0,1
4,0,1,0,1,0,0,0,1,0,1,0,1
5,0,1,0,1,0,0,0,1,1,0,1,0
6,1,0,0,1,0,0,0,1,1,0,0,1
7,0,0,1,0,0,1,1,0,0,1,1,0
8,0,0,1,1,0,0,0,1,0,1,0,1
9,0,1,0,0,0,1,0,1,0,1,0,1
10,0,0,1,0,0,1,0,1,1,0,0,1
11,1,0,0,0,0,1,1,0,1,0,0,1
12,1,0,0,0,1,0,0,1,0,1,0,1
13,0,1,0,0,0,1,1,0,1,0,1,0

In [30]:
X=data.drop(["No", "Yes"], axis=1)
y=data[['Yes']]

## Train nad Test

In [33]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2,random_state=12)

In [35]:
dt=DecisionTreeClassifier()

In [39]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [41]:
y_pred=dt.predict(X_test)
y_pred

array([1, 1, 1], dtype=int64)

In [43]:
print("Confusion matrix:\n", confusion_matrix(y_test,y_pred))

Confusion matrix:
 [[0 1]
 [0 2]]

In [45]:
print("Accuracy Score\n", accuracy_score(y_test,y_pred))

Accuracy Score
 0.6666666666666666

In [47]:
print("Classification report:\n", classification_report(y_test,y_pred))

Classification report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.67      1.00      0.80         2

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3

D:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))